#!/usr/bin/env python3
"""Write SOURCE.md and LICENSE.md in each data/historical/raw/<dataset>/ folder.

The descriptions below were taken from each dataset's official page when it
was downloaded. The file list, sizes and checksums come from manifest.json.
"""
import json
import os

ROOT = os.path.join(os.path.dirname(__file__), '..', '..', 'data', 'historical')
RAW = os.path.join(ROOT, 'raw')
LARGE = 25 * 1024 * 1024  # files above this are not committed; fetch.py restores them

ADS_TERMS = 'ADS Terms of Use and Access: https://archaeologydataservice.ac.uk/terms-and-conditions/'

DATASETS = {
    'tribal-hidage': {
        'name': 'Census Data from Beyond the Tribal Hidage: the early Anglo-Saxon kingdoms of southern Britain AD 450–650',
        'source': 'Archaeology Data Service (ADS), University of York. Creators: Sue Harrington, Stuart Brookes (UCL Institute of Archaeology).',
        'page': 'https://archaeologydataservice.ac.uk/archives/collections/view/1008598/downloads.cfm',
        'doi': 'https://doi.org/10.5284/1136515',
        'version': 'First released 7 October 2025 (data created 2006–2019).',
        'licence': 'Creative Commons Attribution 4.0 International (CC BY 4.0)',
        'licence_url': 'https://creativecommons.org/licenses/by/4.0/',
        'licence_note': 'Data copyright © Dr Stuart Brookes, Dr Sue Harrington. ' + ADS_TERMS,
        'cite': 'Harrington, S., Brookes, S. (2025) Census Data from Beyond the Tribal Hidage: the early Anglo-Saxon kingdoms of southern Britain AD 450-650 [data-set]. York: Archaeology Data Service [distributor] https://doi.org/10.5284/1136515',
        'area': 'Southern England (south of the Humber–Mersey line).',
        'period': 'c. AD 450–650.',
        'contents': 'Early Anglo-Saxon burial census: 834 burial sites (Sites_data.csv, with coordinates), 12,379 buried individuals (Individuals_Data.csv) and 26,043 grave objects (Objects_Data.csv); a general guide (PDF) and a plot of burial sites (JPG). The collection has no kingdom boundary polygons — only these census tables.',
    },
    'domesday': {
        'name': 'Domesday Shires and Hundreds of England',
        'source': 'Archaeology Data Service (ADS). Creator: Stuart Brookes (Landscapes of Governance project, UCL / Nottingham / Winchester).',
        'page': 'https://archaeologydataservice.ac.uk/archives/collections/view/1003676/downloads.cfm',
        'doi': 'https://doi.org/10.5284/1058999',
        'version': 'First released 31 January 2020 (data created 2010–2017).',
        'licence': 'Creative Commons Attribution 4.0 International (CC BY 4.0)',
        'licence_url': 'https://creativecommons.org/licenses/by/4.0/',
        'licence_note': 'Data copyright © Dr Stuart Brookes unless otherwise stated. ' + ADS_TERMS,
        'cite': 'Brookes, S. (2020) Domesday Shires and Hundreds of England [data-set]. York: Archaeology Data Service [distributor] https://doi.org/10.5284/1058999',
        'area': 'England and parts of Wales.',
        'period': 'AD 1086 (as recorded in Domesday Book).',
        'contents': 'All three ESRI shapefiles offered: DBshires (shires, 35), DBinter (intermediate districts such as lathes and rapes, 21) and DBhundreds (hundreds and wapentakes, 810); plus the general guide (PDF). British National Grid.',
        'processed': 'public/world/tiles/domesday.pmtiles (layer `units`; `k` = shire / inter / hundred), built by scripts/atlas-build/england.py. Map layer “Domesday shires & hundreds (1086)”, shown 1066–1106 and always labelled as the 1086 arrangement.',
        'limitations': 'From the guide: the boundaries are a retrogressive reconstruction — mostly following the Alecto Domesday county maps (1986–92) and re-aggregated from parish boundaries mapped in 1851 — of units "as they are believed to have existed in 1086", not earlier or later arrangements. Domesday coverage is thinner in Durham, Northumberland, Westmorland and Cumberland, where land was divided into wards rather than hundreds; parts of Wales and the far north are absent — a gap in the record, not an absence of places. The guide counts 812 hundreds; the file holds 810 polygons. DBinter groups very different units (Ridings, lathes, rapes, Lincolnshire hundreds) together.',
    },
    'medieval-bridges': {
        'name': 'Bridges of Medieval England to c.1250',
        'source': 'Archaeology Data Service (ADS). Creators: Stuart Brookes, Eleanor Rye, Eljas Oksanen (Early Medieval Atlas; Travel and Communications in Anglo-Saxon England project).',
        'page': 'https://archaeologydataservice.ac.uk/archives/collections/view/1003426/downloads.cfm',
        'doi': 'https://doi.org/10.5284/1053676',
        'version': 'First released 25 July 2019.',
        'licence': 'Creative Commons Attribution 4.0 International (CC BY 4.0)',
        'licence_url': 'https://creativecommons.org/licenses/by/4.0/',
        'licence_note': 'Data copyright © UCL Institute of Archaeology unless otherwise stated. ' + ADS_TERMS,
        'cite': 'Brookes, S., Rye, E., Oksanen, E. (2019) Bridges of Medieval England to c.1250 [data-set]. York: Archaeology Data Service [distributor] https://doi.org/10.5284/1053676',
        'area': 'England.',
        'period': 'Early medieval to c. AD 1250.',
        'contents': 'Bridges and fording points attested in documents, archaeological surveys and place-names: Bridges1250 as a shapefile (ZIP) and CSV, plus the general guide (PDF).',
    },
    'inland-navigation': {
        'name': 'Inland Navigation in England and Wales before 1348: GIS Database',
        'source': 'Archaeology Data Service (ADS). Creator: Eljas Oksanen (Early Medieval Atlas).',
        'page': 'https://archaeologydataservice.ac.uk/archives/collections/view/1003427/downloads.cfm',
        'doi': 'https://doi.org/10.5284/1057497',
        'version': 'First released 8 November 2019.',
        'licence': 'Creative Commons Attribution 4.0 International (CC BY 4.0)',
        'licence_url': 'https://creativecommons.org/licenses/by/4.0/',
        'licence_note': 'Data copyright © UCL Institute of Archaeology unless otherwise stated. ' + ADS_TERMS,
        'cite': 'Oksanen, E. (2019) Inland Navigation in England and Wales before 1348: GIS Database [data-set]. York: Archaeology Data Service [distributor] https://doi.org/10.5284/1057497',
        'area': 'England and Wales.',
        'period': '11th century to 1348.',
        'contents': 'Navigable rivers and canals: direct evidence (documents, finds, canal building; 542 segments), indirect evidence (mainly place-names; 110), heads of navigation (249, with latest dates and references), and place-names relating to river traffic (65) — each a shapefile in a ZIP; plus the general guide (PDF). British National Grid.',
        'processed': 'public/world/tiles/navigation.pmtiles (layer `nav`; `k` = direct / indirect / head / pn), built by scripts/atlas-build/england.py. Map layer “Navigable rivers before 1348”, shown 1000–1348.',
        'limitations': 'Courses follow modern Ordnance Survey rivers, parish or county boundaries where the medieval course is unknown (the `Course` field says which). Indirect evidence rests mostly on place-names and cannot be dated precisely. Evidence-class codes (DE, IE, KB) and dates like “PN” or “post-1348” are kept exactly as recorded. Rivers not listed may simply lack surviving evidence.',
    },
    'gough-map': {
        'name': 'The Routes and Roads of the Gough Map: GIS Database',
        'source': 'Archaeology Data Service (ADS). Creators: Eljas Oksanen (University of Helsinki), Stuart Brookes (UCL Institute of Archaeology).',
        'page': 'https://archaeologydataservice.ac.uk/archives/collections/view/1007268/downloads.cfm',
        'doi': 'https://doi.org/10.5284/1124312',
        'version': 'First released 13 November 2024 (data created 2015–2024).',
        'licence': 'Creative Commons Attribution 4.0 International (CC BY 4.0)',
        'licence_url': 'https://creativecommons.org/licenses/by/4.0/',
        'licence_note': 'Data copyright © Eljas Oksanen, Dr Stuart Brookes unless otherwise stated. ' + ADS_TERMS,
        'cite': 'Oksanen, E., Brookes, S. (2024) The Routes and Roads of the Gough Map: GIS Database [data-set]. York: Archaeology Data Service [distributor] https://doi.org/10.5284/1124312',
        'area': 'England and Wales (Great Britain as drawn on the Gough Map).',
        'period': 'The Gough Map (c. 14th–15th century), with routes matched to Roman, medieval and post-medieval evidence.',
        'contents': 'Complete GIS set: the red lines drawn on the map (gough_red_lines, 188), the settlements they connect (gough_way_stations, 179) and the reconstructed routeways matched to the lines (gough_routes, 455), as zipped shapefiles; plus the introduction (PDF). British National Grid.',
        'processed': 'public/world/tiles/gough.pmtiles (layer `gough`; `k` = station / red / route), built by scripts/atlas-build/england.py. Map layer “Gough Map routes (c. 1400)”, shown 1350–1450.',
        'limitations': 'The Gough Map (c. 1400) shows a selection of routes, not the whole medieval network. Red lines are schematic. Routes are reconstructions matched to the lines from Roman, medieval, 17th–18th-century (Cary, Ogilby) and modern evidence. The routes’ numeric `period` code and some fields are not explained in the files held here, so they are shown as recorded, never interpreted. Way stations with legibility 0 are identifications by the map’s editors where the map’s name is illegible.',
    },
    'viabundus': {
        'name': 'Viabundus map of premodern European transport and mobility (Viabundus 2)',
        'source': 'Viabundus project (Bart Holterman, Maria Carina Dengg, Kasper H. Andersen and others), deposited on Zenodo by the project. Project site: https://www.viabundus.eu/',
        'page': 'https://zenodo.org/records/16611998',
        'doi': 'https://doi.org/10.5281/zenodo.16611998',
        'version': 'Version 2, published 25 April 2025 (latest version on Zenodo when downloaded).',
        'licence': 'Creative Commons Attribution 4.0 International (CC BY 4.0)',
        'licence_url': 'https://creativecommons.org/licenses/by/4.0/',
        'licence_note': '',
        'cite': 'Holterman, B. et al. (2025) Viabundus map of premodern European transport and mobility, version 2. Zenodo. https://doi.org/10.5281/zenodo.16611998',
        'area': 'Northern and central Europe (the Hanseatic area and beyond: Low Countries, Germany, Denmark, Scandinavia, the Baltic, Poland and neighbours).',
        'period': '1350–1650.',
        'contents': 'The complete Zenodo release (all 21 files): road and waterway edges (edges.csv plus GeoJSON and GML), places (nodes.csv), towns, town outlines, fairs, tolls and descriptions, population figures, alternative names, the 1500 waterway layer, literature and links, and documentation (PDFs).',
    },
    'itinere': {
        'name': 'Itiner-e: A High-Resolution Dataset of Roads of the Roman Empire',
        'source': 'Itiner-e project (Pau de Soto, Adam Pažout, Tom Brughmans, Peter Bjerregaard Vahlstrup and others; Aarhus University). Project site: https://itiner-e.org/',
        'page': 'https://zenodo.org/records/17122148 and https://itiner-e.org/about (nightly export)',
        'doi': 'https://doi.org/10.5281/zenodo.17122148',
        'version': 'Static version 2024, release 1.3 (Zenodo, 15 September 2025), documented in de Soto et al. 2025, Scientific Data, https://doi.org/10.1038/s41597-025-06140-z. Plus the nightly full export from itiner-e.org on the download date.',
        'licence': 'Creative Commons Attribution 4.0 International (CC BY 4.0)',
        'licence_url': 'https://creativecommons.org/licenses/by/4.0/',
        'licence_note': 'Stated on https://itiner-e.org/about: "Itiner-e: the digital atlas of ancient roads © 2024 by Brughmans, Pažout, de Soto and Bjerregaard Vahlstrup is licensed under CC BY 4.0". The Zenodo record itself carries no licence field.',
        'cite': 'de Soto, P. et al. (2025) A High-Resolution Dataset of Roads of the Roman Empire: Itiner-e static version 2024. Zenodo. https://doi.org/10.5281/zenodo.17122148',
        'area': 'The Roman Empire (Europe, North Africa, the Near East).',
        'period': 'c. 300 BCE – 300 CE.',
        'contents': 'The complete static release: all roads as GeoPackage, GeoJSON and a full shapefile set, the bibliography (BibTeX) and a field description (DOCX). nightly-export/ holds the project\'s own full nightly export (NDJSON, one route segment per line, including rivers and sea lanes and nearby Pleiades places), which grows as the project adds data.',
    },
    'pleiades': {
        'name': 'Pleiades: a gazetteer of past places',
        'source': 'Pleiades (Institute for the Study of the Ancient World, NYU, and contributors). Official downloads: https://atlantides.org/downloads/pleiades/',
        'page': 'https://atlantides.org/downloads/pleiades/',
        'doi': '',
        'version': 'Daily export of 29 September 2026 (files are dated in their names).',
        'licence': 'Creative Commons Attribution (CC BY)',
        'licence_url': 'https://creativecommons.org/licenses/',
        'licence_note': 'Stated on https://pleiades.stoa.org/: "Pleiades content is governed by the copyrights of the individual contributors responsible for its creation. Some rights are reserved. All content is distributed under the terms of a Creative Commons Attribution license (cc-by)." The licence version is not stated on that page.',
        'cite': 'Pleiades: A Gazetteer of Past Places. https://pleiades.stoa.org/ (daily export, 29 September 2026).',
        'area': 'The ancient Mediterranean, Near East and beyond (Europe, North Africa, western and central Asia).',
        'period': 'Mainly c. 1000 BCE – AD 640, with some earlier and later places.',
        'contents': 'The complete GIS package (pleiades_gis_data.zip: places, names, locations and connections as CSV/GIS tables), the comprehensive JSON of all places (pleiades-places-*.json.gz) and the errata JSON, and the daily CSV dumps of places, names and locations with their README.',
    },
    'al-thurayya': {
        'name': 'al-Ṯurayyā Gazetteer (v1.0)',
        'source': 'al-Ṯurayyā project (Masoumeh Seydi, Maxim Romanov, Leipzig; after Georgette Cornu, Atlas du monde arabo-islamique à l\'époque classique, 1983). Official repository: https://github.com/althurayya/althurayya.github.io',
        'page': 'https://github.com/althurayya/althurayya.github.io/tree/f244e65ddf782baef08e410870c61c8096ff9f90/master',
        'doi': '',
        'version': 'Repository commit f244e65ddf782baef08e410870c61c8096ff9f90 (22 September 2026).',
        'licence': 'Data: Creative Commons Attribution 4.0 International (CC BY 4.0), see DATA-LICENSE.md. Code: Apache License 2.0, see LICENSE.',
        'licence_url': 'https://creativecommons.org/licenses/by/4.0/',
        'licence_note': 'The README says source-derived and third-party material is excluded from CC BY 4.0 unless its own terms allow it. The original DATA-LICENSE.md, LICENSE and README.md are kept in original/.',
        'cite': 'Seydi, M., Romanov, M. et al. al-Ṯurayyā Gazetteer, v1.0. https://althurayya.github.io/',
        'area': 'The early Islamic world, from al-Andalus and the Maghreb to Central Asia.',
        'period': 'Classical Islamic period, 9th–10th centuries CE (after Cornu).',
        'contents': 'The data files the map uses (master/): places (GeoJSON/JSON, in several structures, over 2,000 toponyms), routes (JSON, almost as many route sections) and regions. The World Historical Gazetteer copy could not be checked: whgazetteer.org refused automated access (HTTP 403).',
    },
    'living-with-machines': {
        'name': 'Living with Machines: railspace and building datasets (MapReader)',
        'source': 'Living with Machines (The Alan Turing Institute / British Library), using National Library of Scotland maps. Listed on the NLS Data Foundry: https://data.nls.uk/data/map-spatial-data/living-with-machines-railspace-building/ — the data itself is on Zenodo.',
        'page': 'https://data.nls.uk/data/map-spatial-data/living-with-machines-railspace-building/',
        'doi': 'https://doi.org/10.5281/zenodo.7147906 (linked from the Data Foundry); https://doi.org/10.5281/zenodo.11241371; https://doi.org/10.5281/zenodo.14522926',
        'version': 'SIGSPATIAL 2022 data v0.3.3 (5 October 2022); annotations 2024 (22 May 2024); railspace v2 (19 December 2024).',
        'licence': 'Creative Commons Attribution 4.0 International (CC BY 4.0)',
        'licence_url': 'https://creativecommons.org/licenses/by/4.0/',
        'licence_note': 'All three Zenodo records and the Data Foundry page state CC BY 4.0.',
        'cite': 'Living with Machines / MapReader. MapReader_Data_SIGSPATIAL_2022 (Zenodo 7147906); MapReader_railspace_and_building_annotations_2024 (Zenodo 11241371); MapReader_railspace_v2 (Zenodo 14522926).',
        'area': 'England, Wales and Scotland.',
        'period': 'Ordnance Survey six-inch 2nd edition maps, 1888–1913.',
        'contents': 'sigspatial-2022: the dataset the Data Foundry links to (gold-standard annotations and machine-labelled 100 m patches for railspace and buildings). annotations-2024: post-processed railspace and building annotations, including georeferenced CSVs. railspace-v2: updated railspace predictions for 586,276 patches. Not downloaded: maps.zip and slice_meters_100_100.zip from the 2024 record (3.4 GB of map image tiles, not spatial data).',
    },
    'historic-england': {
        'name': 'National Heritage List for England (NHLE) — Historic England open data',
        'source': 'Historic England Open Data Hub: https://opendata-historicengland.hub.arcgis.com/ (item 767f279327a24845bf47dfe5eae9862b)',
        'page': 'https://opendata-historicengland.hub.arcgis.com/datasets/767f279327a24845bf47dfe5eae9862b',
        'doi': '',
        'version': 'Export made on the download date (Historic England says the data is updated daily). Re-downloading gives a newer export with a different checksum.',
        'licence': 'Open Government Licence v3.0, under the Historic England Open Data Hub Terms and Conditions',
        'licence_url': 'https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/',
        'licence_note': 'Item metadata: "© Crown Copyright 2026. Contains Ordnance Survey data © Crown copyright and database right 2026. Released under OGL." Licence field: "Historic England Open Data Hub Terms and Conditions". The terms page on historicengland.org.uk refused automated access (bot check), so its full text is not saved here.',
        'cite': '© Historic England 2026. Contains Ordnance Survey data © Crown copyright and database right 2026. National Heritage List for England.',
        'area': 'England.',
        'period': 'Designated heritage from prehistory to the 20th century; designation dates from the 1880s onward.',
        'contents': 'GeoPackage exports (British National Grid, EPSG:27700) of the six requested designations: Listed Buildings (points, 379,685, and polygons for entries listed or amended since April 2011), Scheduled Monuments, Registered Parks and Gardens, Registered Battlefields, Protected Wreck Sites and World Heritage Sites.',
    },
    'cshapes': {
        'name': 'CShapes 2.0',
        'source': 'ETH Zürich, International Conflict Research (Schvitz, Girardin, Rüegger, Weidmann, Cederman, Gleditsch). https://icr.ethz.ch/data/cshapes/',
        'page': 'https://icr.ethz.ch/data/cshapes/',
        'doi': '',
        'version': 'CShapes 2.0 (see ChangeLog.txt).',
        'licence': 'Creative Commons Attribution-NonCommercial-ShareAlike 4.0 (CC BY-NC-SA 4.0)',
        'licence_url': 'https://creativecommons.org/licenses/by-nc-sa/4.0/',
        'licence_note': 'NON-COMMERCIAL ONLY. Anything built from it must be shared under the same licence. Fine for personal, non-commercial use of Shelf; it must not be used if Shelf is ever sold or monetised.',
        'cite': 'Schvitz, G., Girardin, L., Rüegger, S., Weidmann, N. B., Cederman, L.-E., Gleditsch, K. S. (2022) Mapping the International System, 1886-2019: The CShapes 2.0 Dataset. Journal of Conflict Resolution 66(1).',
        'area': 'World (independent states and dependent territories); CShapes-Europe from 1816.',
        'period': '1886–2019 (Europe from 1816).',
        'contents': 'State borders and capitals with validity dates: shapefile (ZIP), GeoJSON, CSV, the Europe-from-1816 GeoJSON, the codebook (PDF), the readme text and the changelog. The SQL, XLSX and R-package formats were skipped as duplicates.',
    },
    'atlas-rural-settlement': {
        'name': 'Atlas of Rural Settlement in England GIS (Roberts & Wrathmell)',
        'source': 'English Heritage (now Historic England), data by Andrew Lowerre, Eddie Lyons, Brian K. Roberts and Stuart Wrathmell; distributed by ADS and Historic England.',
        'page': 'https://archaeologydataservice.ac.uk/archives/view/atlasrural_he_2015/downloads.cfm',
        'doi': 'https://doi.org/10.5284/1031493',
        'version': 'Shapefile dissemination package, README dated January 2011 (English Heritage); ADS collection 2015. Based on Roberts & Wrathmell, An Atlas of Rural Settlement in England (2000; corrected reprint 2003).',
        'licence': 'Atlas of Rural Settlement in England GIS terms and conditions (© English Heritage) — download for personal and business use',
        'licence_url': 'https://archaeologydataservice.ac.uk/archives/view/atlasrural_he_2015/',
        'licence_note': 'From AtlasRuralSettlementEnglandGIS_TermsConditions.pdf inside the ZIP: title, copyright and all other rights remain with English Heritage, Brian Roberts and Stuart Wrathmell; the data may be downloaded "for personal and business use"; it must not be used in ways that may damage archaeological sites, historic buildings or landscapes; no warranty. The terms do NOT grant permission to republish the data. Because this repository and the Shelf website are public, the processed tiles are kept out of git and out of the deployed site (local builds only). The raw ZIP was uploaded to this public repository by its owner; consider removing it, or ask Historic England for permission to republish.',
        'cite': 'Lowerre, A., Lyons, E., Roberts, B. K., Wrathmell, S. (2015) Atlas of Rural Settlement in England GIS [data-set]. York: Archaeology Data Service [distributor] https://doi.org/10.5284/1031493',
        'area': 'England (with a background outline of England and Wales).',
        'period': 'Settlement patterns mapped mainly from mid-nineteenth-century Ordnance Survey maps, used to study medieval and earlier rural settlement. Not a dated snapshot of any one year.',
        'contents': 'The complete Shapefile package: settlement provinces (31 polygons), sub-provinces (60), local regions (276, with dispersion descriptions), nucleations (10,513 villages and hamlets by category), dispersion/hamlet scores (4,004 sample points), terrain types, terrain zones and escarpments, an England–Wales background, UK GEMINI metadata, ArcGIS project and layer files, the province descriptions (PDF), documentation and data dictionary (PDFs), terms and conditions (PDF) and READ_ME.txt.',
        'processed': 'public/world/tiles/rural-settlement.pmtiles (layer `rural`; `k` = province / subprovince / local / nucleation), built by scripts/atlas-build/england.py — git-ignored and not deployed. The map layer “Rural settlement provinces (England)” is disabled unless Shelf is built locally with VITE_SHELF_LOCAL_DATA=1.',
        'limitations': 'A characterisation of settlement patterns, not a record of when places existed. Terrain layers were not processed (not needed yet). English Heritage says the data should be checked against other sources before relying on it.',
    },
    'wikidata-medieval': {
        'name': 'Wikidata snapshot: medieval and early sites of Europe, the Mediterranean and the Near East',
        'source': 'Wikidata (Wikimedia Foundation and contributors), queried through the QLever Wikidata endpoint (University of Freiburg), https://qlever.dev/wikidata',
        'page': 'https://www.wikidata.org/',
        'doi': '',
        'version': 'Query snapshot; the exact SPARQL queries are saved in original/queries/. Re-run with scripts/historical-data/wikidata_snapshot.py.',
        'licence': 'Creative Commons CC0 1.0 (public domain dedication)',
        'licence_url': 'https://creativecommons.org/publicdomain/zero/1.0/',
        'licence_note': 'Wikidata structured data is CC0 (https://www.wikidata.org/wiki/Wikidata:Licensing). Attribution is not required but is given.',
        'cite': 'Wikidata contributors, Wikidata (snapshot via QLever). https://www.wikidata.org/',
        'area': 'Europe, the Mediterranean and the Near East (lon −32…62, lat 24…72).',
        'period': 'Castles, monasteries, cathedrals and dioceses of any date (with Wikidata\'s founding / dissolution dates where recorded); battles and sieges before 1600; fortifications founded before 1500; universities and bridges founded before 1600; settlements with a first written mention or founding date 400–1600.',
        'contents': 'Per kind: the item, coordinates, English label, founding date (P571), earliest written record (P1249), dissolution (P576), point in time / start / end (P585, P580, P582), religious order (P611), diocese (P708), part of (P361, e.g. the war of a battle), instance-of classes and sitelink count; a second file with the item\'s labels in 27 European languages and Latin; and English labels of the orders, classes, dioceses and wars referred to. original/temporal-evidence.json (scripts/historical-data/wikidata_dates.py, Wikidata Query Service): for the items with none of those dates, their other dated statements — significant events with a date (P793), official opening (P1619), start of an instance-of statement (P31 + P580), and time period (P2348), architectural style (P149) and culture (P2596) with the dates Wikidata records for those items.',
        'processed': 'public/world/tiles/medieval-sites.pmtiles and the place index (gazetteer `wikidata`), built by scripts/atlas-build/sites.py.',
        'limitations': 'Coverage follows what Wikipedians and national heritage imports have entered, not historical reality: e.g. 9,400 Czech settlements have a first-mention date but only a few hundred French ones, although France has far more medieval villages. Many castles and monasteries have no founding date (only 16% of castles), and the "castle" class also holds later château / Schloss country houses. Dates are often the first mention, the start of building, or a refoundation — Wikidata does not always say which. Coordinates are of the present site or ruin. Battle locations are Wikidata\'s, not a battlefield survey.',
    },
    'germania-sacra': {
        'name': 'Germania Sacra: Klöster und Stifte des Alten Reiches (Database of Monasteries)',
        'source': 'Germania Sacra, Niedersächsische Akademie der Wissenschaften zu Göttingen; API run by SUB Göttingen.',
        'page': 'https://adw-goe.de/germania-sacra/klosterdatenbank/datenservice/ (API: https://api.gs.sub.uni-goettingen.de)',
        'doi': '',
        'version': 'Live API as downloaded (the database is continuously edited).',
        'licence': 'Creative Commons Attribution-ShareAlike 3.0 (CC BY-SA 3.0)',
        'licence_url': 'https://creativecommons.org/licenses/by-sa/3.0/',
        'licence_note': 'Stated in the API documentation on the Datenservice page. Anything derived from it (the tiles built by Shelf) is shared under the same licence, with attribution.',
        'cite': 'Germania Sacra, Klöster und Stifte des Alten Reiches, Niedersächsische Akademie der Wissenschaften zu Göttingen. https://klosterdatenbank.germania-sacra.de/',
        'area': 'The Holy Roman Empire and neighbouring areas (Germany, Austria, Switzerland, the Low Countries, Bohemia, Alsace-Lorraine, northern Italy fringes).',
        'period': 'Early Middle Ages to the secularisation (c. 700–1810), with each order\'s tenure dated.',
        'contents': 'monasteries-locations.geojson: 7,473 located monasteries, canonries and houses (points) with their name, place and each religious order that held them, dated as written in the source (e.g. "zwischen 712 und 714") and as a machine year (beginTPQ / endTPQ); monasteries-list.json: first page of the list endpoint; diocese-borders.geojson: 67 diocese polygons.',
        'processed': 'public/world/tiles/medieval-sites.pmtiles (houses) and the place index (gazetteer `germaniasacra`), built by scripts/atlas-build/sites.py.',
        'limitations': 'Coverage is the Empire only. The diocese borders are the database\'s own reconstruction for no single stated date. A house that moved has one row per location. Dates are termini post/ante quos, not exact.',
    },
    'buringh-urban': {
        'name': 'European urban population, 700–2000',
        'source': 'E. Buringh (Utrecht University), deposited at DANS Data Station Social Sciences and Humanities.',
        'page': 'https://ssh.datastations.nl/dataset.xhtml?persistentId=doi:10.17026/dans-xzy-u62q',
        'doi': 'https://doi.org/10.17026/dans-xzy-u62q',
        'version': 'Version 1 (production 2020-05-05; distributed 2021-03-31).',
        'licence': 'Creative Commons CC0 1.0',
        'licence_url': 'https://creativecommons.org/publicdomain/zero/1.0/',
        'licence_note': 'Licence field of the DANS record.',
        'cite': 'Buringh, E. (2021) European urban population, 700–2000. DANS. https://doi.org/10.17026/dans-xzy-u62q',
        'area': 'Europe (2,262 settlements, all present-day European countries).',
        'period': 'AD 700–2000, estimates per century (and finer after 1500).',
        'contents': 'One row per city and year: city, historical names and synonyms, country, transport location / water catchment, coordinates, elevation, estimated inhabitants (thousands), the source of the estimate and its nature (e.g. "proxied", imputed). Annexes A and B (PDF) document the sources and method.',
        'processed': 'Population estimates for towns in the place index and map sizes (scripts/atlas-build/sites.py).',
        'limitations': 'Many figures are proxies or city-specific imputations, marked as such; a population of 0 means below the dataset\'s threshold, not "did not exist". Coordinates are rounded to 0.01°.',
    },
    'hced': {
        'name': 'Historical Conflict Event Dataset (HCED)',
        'source': 'Charles Miller (Australian National University) and co-authors, Harvard Dataverse.',
        'page': 'https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/6ZFC0V',
        'doi': 'https://doi.org/10.7910/DVN/6ZFC0V',
        'version': 'Dataverse version 5; data file "HCED Data v3.csv".',
        'licence': 'Creative Commons CC0 1.0',
        'licence_url': 'https://creativecommons.org/publicdomain/zero/1.0/',
        'licence_note': 'Licence field of the Dataverse record.',
        'cite': 'Miller, C. et al. (2022) Conflict Events Worldwide Since 1468BC: Introducing the Historical Conflict Event Dataset. Journal of Conflict Resolution. https://doi.org/10.1177/00220027221119085 ; data: https://doi.org/10.7910/DVN/6ZFC0V',
        'area': 'Worldwide.',
        'period': '1468 BC – present.',
        'contents': 'About 7,000 battles and sieges with year, coordinates, participants, war, winner and loser, theatre, scale, and the reference work (mostly encyclopedias of warfare). The explainer file describes the replication files, which were not downloaded.',
        'processed': 'Battles not already in the Wikidata snapshot are added to the medieval-sites tiles (scripts/atlas-build/sites.py).',
        'limitations': 'Geolocated first with Google Maps from battle names, then checked by hand; the authors list locations that differ from other datasets by more than 100 km. Year only; no exact dates. Coverage follows English-language warfare encyclopedias.',
    },
    'periodo': {
        'name': 'PeriodO: a gazetteer of period definitions',
        'source': 'PeriodO project (Ryan Shaw, Adam Rabinowitz and others).',
        'page': 'https://perio.do/',
        'doi': '',
        'version': 'Full dataset (d.json) as downloaded.',
        'licence': 'Creative Commons CC0 1.0',
        'licence_url': 'https://creativecommons.org/publicdomain/zero/1.0/',
        'licence_note': 'PeriodO publishes its period definitions under CC0.',
        'cite': 'PeriodO, a gazetteer of period definitions. https://perio.do/',
        'area': 'Worldwide.',
        'period': 'All periods.',
        'contents': 'Scholarly definitions of named periods (e.g. "Late Antique", "High Middle Ages" for a region), each with its source, spatial coverage and start/end ranges.',
        'limitations': 'Reference only: kept to check what a period name means for a region. Not yet used by the app.',
    },
    'princes-townspeople': {
        'name': 'Princes and Townspeople: A Collection of Historical Statistics on German Territories and Cities (parts 1–6)',
        'source': 'Edyta P. Bogucka, Davide Cantoni, Cathrin Mohr, Matthias Weigand (TU Munich / LMU Munich); Harvard Dataverse.',
        'page': 'https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/ZGSJED (and DVN/GZPPVE, TYAGVO, FJ8ZZQ, JIAC0S, ZN1QNS)',
        'doi': 'https://doi.org/10.7910/DVN/ZGSJED',
        'version': 'Part 1 v3 (2021), part 2 v4 (2024), parts 3–4 v1 (2020), part 5 v2 (2024), part 6 v1 (2021) — the latest versions when downloaded.',
        'licence': 'Creative Commons CC0 1.0 (each Dataverse record)',
        'licence_url': 'https://creativecommons.org/publicdomain/zero/1.0/',
        'licence_note': 'Licence field of each of the six Dataverse records.',
        'cite': 'Bogucka, E. P., Cantoni, D., Mohr, C., Weigand, M. Princes and Townspeople: A Collection of Historical Statistics on German Territories and Cities. Harvard Dataverse. https://doi.org/10.7910/DVN/ZGSJED',
        'area': 'The Holy Roman Empire / German Empire within the borders of Germany 1937 (incl. Danzig): the 2,390 cities of the Deutsches Städtebuch.',
        'period': 'First mentions from the early Middle Ages; ruling territory per year 1300–1918 (reliable from 1300 per the documentation).',
        'contents': 'City locations and 2019 borders; territorial histories (ruling lineage per city per year, dynasties, territory codes); town charters and first mentions (with date uncertainty and range, legal families); market grants by type; construction activity; conflict incidents. Documentation PDFs for each part.',
        'processed': 'public/world/tiles/hre-towns.pmtiles and place-index gazetteer `hre` (scripts/atlas-build/regional.py): first mention, charter, first market grant and ruler spans. Construction and conflict tables are held raw, not yet used.',
        'limitations': 'Only towns that later became cities (Städtebuch); villages are not covered. Coverage limited to 1937 German borders (Bohemia, Austria, Switzerland, Low Countries excluded). Dates come from the Städtebuch entries, coded with uncertainty/range fields.',
    },
    'merimee': {
        'name': 'Immeubles protégés au titre des Monuments historiques (base Mérimée)',
        'source': 'Ministère de la Culture (France), Plateforme ouverte du patrimoine (POP); published on data.gouv.fr.',
        'page': 'https://www.data.gouv.fr/datasets/immeubles-proteges-au-titre-des-monuments-historiques-2/',
        'doi': '',
        'version': 'Export updated 2026-09-24 (data.gouv.fr last modified).',
        'licence': 'Licence Ouverte / Open Licence 2.0 (Etalab)',
        'licence_url': 'https://www.etalab.gouv.fr/licence-ouverte-open-licence/',
        'licence_note': 'Licence field "lov2" of the data.gouv.fr dataset.',
        'cite': 'Ministère de la Culture, base Mérimée — Immeubles protégés au titre des Monuments historiques, Licence Ouverte 2.0.',
        'area': 'France (incl. overseas).',
        'period': 'Prehistory to the 20th century; dated by century of construction campaigns.',
        'contents': 'About 46,760 protected buildings with denomination, century of main and secondary building campaigns, history text, commune, WGS84 coordinates (44,502 located).',
        'processed': 'Medieval monuments (main campaign before 1500) of the kinds castle, religious building, bridge and market hall — 12,235 — are joined to Wikidata sites within 250 m (2,360) or added as sites (gazetteer `merimee`), dated by their building-campaign century as an evidence period.',
        'limitations': 'A protection register, not an inventory of medieval sites: unprotected and vanished buildings are absent. The century is when the present building was mainly built; the site may be older.',
    },
    'finland-heritage': {
        'name': 'Museovirasto spatial data: archaeological sites and protected buildings (research dataset)',
        'source': 'Finnish Heritage Agency (Museovirasto).',
        'page': 'https://www.museovirasto.fi/fi/palvelut-ja-ohjeet/tietojarjestelmat/kulttuuriympariston-tietojarjestelmat/kulttuuriympaeristoen-paikkatietoaineistot',
        'doi': '',
        'version': 'Daily export as downloaded (files dated 2026-09-30).',
        'licence': 'Creative Commons Attribution 4.0 International (CC BY 4.0)',
        'licence_url': 'https://creativecommons.org/licenses/by/4.0/',
        'licence_note': '"Museoviraston paikkatiedot on julkaistu Creative Commons CC By 4.0 -lisenssillä." (download page)',
        'cite': 'Museovirasto, Muinaisjäännösrekisteri (CC BY 4.0).',
        'area': 'Finland.',
        'period': 'Stone Age to modern, by period class.',
        'contents': 'GeoPackages of archaeological sites (points and areas; 112,707 point records), protected buildings, nationally significant environments and world heritage (ETRS-TM35FIN).',
        'processed': 'Sites whose period classes include "keskiaikainen" (medieval), 1,823, as gazetteer `finreg` and sites, dated by the period classes only.',
        'limitations': 'Period classes, not dates; the class bounds used by Shelf (medieval c. 1150–1550, Iron Age –1150, historical 1150–) are approximate.',
    },
    'western-bohemia-toponyms': {
        'name': 'Toponymic Data for Western Bohemia up to AD 1500',
        'source': 'Viktorie Janovská; Zenodo.',
        'page': 'https://zenodo.org/records/21479034',
        'doi': 'https://doi.org/10.5281/zenodo.21479034',
        'version': '1.0.0 (2026-07-21).',
        'licence': 'Creative Commons Attribution 4.0 International (CC BY 4.0)',
        'licence_url': 'https://creativecommons.org/licenses/by/4.0/',
        'licence_note': 'License for Dataset.txt in the record.',
        'cite': 'Janovská, V. (2026) Toponymic Data for Western Bohemia up to AD 1500. Zenodo. https://doi.org/10.5281/zenodo.21479034',
        'area': 'Western Bohemia (Plzeň and Karlovy Vary regions).',
        'period': 'Attestations up to 1500.',
        'contents': '1,935 place names with Czech and German names, first and second attestation years and sources, original written form, etymology, coordinates.',
        'processed': 'Joined to Wikidata settlements with the same Czech name within 2 km (980: adds the attested form and, when earlier, the first-mention year) or added as gazetteer `wbohemia` (839).',
    },
    'markets-fairs': {
        'name': 'Gazetteer of Markets and Fairs in England and Wales to 1516 (database)',
        'source': 'Samantha Letters, Centre for Metropolitan History (IHR); SAS-Space repository.',
        'page': 'https://sas-space.sas.ac.uk/106/',
        'doi': '',
        'version': 'SAS-Space deposit (files: MarketsFairs.mdb, MFEngland.txt, MFWales.txt, guide).',
        'licence': 'Not stated — SAS-Space marks the files "UNSPECIFIED". Licence not verified.',
        'licence_url': 'https://sas-space.sas.ac.uk/106/',
        'licence_note': 'LOCAL USE ONLY: kept out of the public repository and public builds until a licence is confirmed.',
        'cite': 'Letters, S. (2003/2010) Gazetteer of Markets and Fairs in England and Wales to 1516. Centre for Metropolitan History / List and Index Society.',
        'area': 'England and Wales.',
        'period': 'To 1516.',
        'contents': '2,395 places, 2,604 markets and 2,934 fairs with OS grid references, grant/charter year, first record, type of evidence, borough status, mint and 1334 valuation.',
        'processed': 'Local-only tiles (local-sites.pmtiles), layer "Market rights & fairs" in local builds.',
    },
    'atlas-fontium-poland': {
        'name': 'Atlas historyczny Polski XVI w. — Atlas Fontium / OntoHGIS (Crown of Poland, second half of the 16th century)',
        'source': 'Department of Historical Atlas, Institute of History, Polish Academy of Sciences (IH PAN).',
        'page': 'https://atlasfontium.pl/ (GeoNode: https://geonode.ontohgis.pl/)',
        'doi': '',
        'version': 'WFS snapshot of the 16th-century layers, 2026-09-30.',
        'licence': 'Not specified (GeoNode licence field "not_specified"; restriction code "intellectualPropertyRights"). Licence not verified.',
        'licence_url': 'https://geonode.ontohgis.pl/',
        'licence_note': 'LOCAL USE ONLY until IH PAN confirms a licence. Not "private use only" by any stated term — simply no licence found.',
        'cite': 'Atlas historyczny Polski. Mapy szczegółowe XVI wieku, IH PAN; Atlas Fontium, https://atlasfontium.pl/',
        'area': 'Crown of the Kingdom of Poland (without Royal Prussia\'s full detail and without the Grand Duchy of Lithuania).',
        'period': 'Second half of the 16th century (tax-register snapshot); one period for the whole layer.',
        'contents': 'Settlements (24,092: character, ownership, owner, size band, parish, mills and inns), parishes, deaneries, archdeaconries, dioceses, districts (powiaty), voivodeships, roads with weights, rivers, forests, water bodies.',
        'processed': 'Settlements and parish seats → local-only site tiles, dated by the atlas period (evidence period, not the places\' own dates). Other layers raw only.',
    },
    'ran-romania': {
        'name': 'Repertoriul Arheologic Național (RAN) — national archaeological register of Romania',
        'source': 'Institutul Național al Patrimoniului / CIMEC. List pages from ran.cimec.ro; positions from the public ArcGIS service behind map.cimec.ro.',
        'page': 'https://ran.cimec.ro/',
        'doi': '',
        'version': 'Snapshot 2026-09-30: 29,052 sites (59 list pages of 500, ordered by period) and their positions.',
        'licence': 'Open Government Licence as listed on data.gov.ro (seen through a search result; data.gov.ro refuses connections from this environment). Not verified.',
        'licence_url': 'https://data.gov.ro/',
        'licence_note': 'PRIVATE DATA PACK: used privately in Shelf, not republished.',
        'cite': 'Repertoriul Arheologic Național, CIMEC — Institutul de Memorie Culturală, https://ran.cimec.ro/',
        'area': 'Romania.',
        'period': 'All periods; Shelf keeps sites with a migration-period or medieval component (400–1600), dated by the stated century where given.',
        'contents': 'Site code, name, category, type, county, locality, components and period; point positions.',
        'processed': '2,865 dated sites → private data pack (settlements, churches, monasteries, fortifications, sites).',
    },
    'dicotopo': {
        'name': 'Dictionnaire topographique de la France (DicoTopo)',
        'source': 'Comité des travaux historiques et scientifiques (CTHS) and École nationale des chartes; XML from github.com/chartes/dico-topo (commit in original/COMMIT). Commune positions: Wikidata items with an INSEE code (QLever, query in original/insee-coords.rq).',
        'page': 'https://dicotopo.cths.fr/',
        'doi': '',
        'version': '53 départements (XML), 2026-09-30.',
        'licence': 'Creative Commons BY-NC-ND 3.0 FR (stated in each XML file and the repository README).',
        'licence_url': 'https://creativecommons.org/licenses/by-nc-nd/3.0/fr/',
        'licence_note': 'PRIVATE DATA PACK: the no-derivatives term rules out republishing transformed data; used privately in Shelf.',
        'cite': 'Dictionnaire topographique de la France, CTHS / École nationale des chartes, https://dicotopo.cths.fr/',
        'area': 'The 53 French départements with a published dictionary.',
        'period': 'Old name forms from the early Middle Ages onwards, each with its date and source.',
        'contents': 'Place articles: headword, type, commune (INSEE code), dated old forms with references.',
        'processed': '22,366 communes (first attestation = earliest dated form, all dated forms kept as historical names) and 6,774 castles, churches and religious houses located by commune (approximate) → private data pack.',
    },
    'darmc': {
        'name': 'DARMC scholarly datasets (Digital Atlas of Roman and Medieval Civilizations)',
        'source': 'Harvard University (M. McCormick et al.), Harvard Dataverse.',
        'page': 'https://dataverse.harvard.edu/dataverse/darmc',
        'doi': '10.7910/DVN/ZIQPDG; 10.7910/DVN/23984; 10.7910/DVN/3KQFUT; 10.7910/DVN/24697',
        'version': 'Shipwrecks AD 1–1500 (2008), Carolingian coin hoards 751–987 (v1.1), ancient ports and harbours (v1.1), rural Anglo-Saxon settlements.',
        'licence': 'No licence stated on these Dataverse records.',
        'licence_url': 'https://dataverse.harvard.edu/dataverse/darmc',
        'licence_note': 'PRIVATE DATA PACK: used privately in Shelf, not republished.',
        'cite': 'McCormick, M. et al., DARMC Scholarly Data Series, Harvard Dataverse.',
        'area': 'Mediterranean and Europe.',
        'period': 'AD 1–1500.',
        'contents': 'Spreadsheets with coordinates and date ranges.',
        'processed': 'Shipwrecks after 400, Carolingian hoards and Anglo-Saxon settlements (843 records) → private data pack; ports raw only (mostly ancient).',
    },
    'ebidat': {
        'name': 'EBIDAT — castle database of the European Castle Institute',
        'source': 'Europäisches Burgeninstitut (Deutsche Burgenvereinigung). Pages snapshotted by scripts/historical-data/ebidat_snapshot.py.',
        'page': 'https://www.ebidat.de/',
        'doi': '',
        'version': 'Snapshot 2026-09-30: 8,264 castles (overview and main-data page per id, ids 1–12000).',
        'licence': 'Not stated.',
        'licence_url': 'https://www.ebidat.de/impressum.html',
        'licence_note': 'PRIVATE DATA PACK: used privately in Shelf, not republished.',
        'cite': 'EBIDAT — Burgendatenbank des Europäischen Burgeninstitutes, https://www.ebidat.de/',
        'area': 'Germany, Austria, Czechia, Slovakia, Hungary, Latvia, Denmark, Finland, the Netherlands.',
        'period': 'Castles dated by the start and end of their use, usually to a half or quarter century.',
        'contents': 'Name, state, region, type, classification, function, dating begin/end, condition, history, position.',
        'processed': 'Castles with their dating span (start = earliest year the dating allows) → private data pack.',
    },
    'sweden-lamningar': {
        'name': 'Lämningar i Sverige — ancient remains of Sweden (Kulturmiljöregistret)',
        'source': 'Riksantikvarieämbetet (Swedish National Heritage Board), pub.raa.se.',
        'page': 'https://pub.raa.se/nedladdning/datauttag/lamningar_v1/',
        'doi': '',
        'version': 'GeoPackage of 2026-09-30.',
        'licence': 'Not stated on the download page; not verified.',
        'licence_url': 'https://www.raa.se/hitta-information/oppna-data/',
        'licence_note': 'PRIVATE DATA PACK: used privately in Shelf, not republished.',
        'cite': 'Riksantikvarieämbetet, Kulturmiljöregistret — lämningar.',
        'area': 'Sweden.',
        'period': 'All periods; Shelf keeps remains dated to the Iron Age or Middle Ages.',
        'contents': 'Remains with type, dating and geometry.',
        'processed': 'Iron Age / medieval remains → private data pack.',
    },
    'engel-hungary': {
        'name': 'Engel Pál: Magyarország a középkor végén (Hungary in the Late Middle Ages), renewed edition 2020/2021',
        'source': 'HUN-REN BTK Institute of History (Árpád-ház Program).',
        'page': 'https://tti.abtk.hu/cikkek/egyeb-hirek/megujult-engel-pal-adatbazisa-a-kozepkori-magyarorszag-digitalis-atlasza',
        'doi': '',
        'version': 'Engel2020.zip (Windows installer Engel2021_setup.exe + user guide).',
        'licence': 'Not stated.',
        'licence_url': 'https://tti.abtk.hu/',
        'licence_note': 'Kept in the vault only. The data sit in an encrypted database inside a Windows GIS program whose only export is attribute tables without coordinates; not integrated.',
        'cite': 'Engel Pál, Magyarország a középkor végén. Digitális térkép és adatbázis, HUN-REN BTK TTI.',
        'area': 'Kingdom of Hungary.',
        'period': 'c. 1500, with landholding in 1382, 1439 and 1490s.',
        'contents': 'Over 23,000 settlements, castles and monasteries; counties; landholding.',
        'processed': 'Not processed (encrypted).',
    },
    'norway-kulturminner': {
        'name': 'Kulturminner — lokaliteter, enkeltminner og sikringssoner (Norwegian heritage register)',
        'source': 'Riksantikvaren, distributed by Geonorge (whole-country GML order).',
        'page': 'https://kartkatalog.geonorge.no/metadata/c72906a0-2bc2-41d7-bea2-c92d368e3c49',
        'doi': '',
        'version': 'GML extract of 2026-09-28; code lists from register.geonorge.no.',
        'licence': 'Norsk lisens for offentlige data (NLOD) — "Åpne data" (Geonorge metadata).',
        'licence_url': 'https://data.norge.no/nlod/no/1.0',
        'licence_note': 'Open licence with attribution; derived tiles are public.',
        'cite': 'Riksantikvaren, Kulturminnesøk / Askeladden, via Geonorge (NLOD).',
        'area': 'Norway.',
        'period': 'All periods; Shelf keeps monuments the register dates to the Migration period, Viking Age or Middle Ages (period codes 044–053).',
        'contents': 'Localities and individual monuments with type, original function, dating code and quality, geometry.',
        'processed': 'Settlements, churches and churchyards, forts, trade sites, burial mounds and house sites with a period of at most 700 years → public tiles and place index (8,941).',
    },
    'nordic-spatial-humanities': {
        'name': 'Nordic Spatial Humanities (source data)',
        'source': 'Zenodo record 14871254: saints\' cult places of the Nordic countries, Icelandic Saga Map places, Old Norse chronicle attestations, Norwegian place-name database.',
        'page': 'https://doi.org/10.5281/zenodo.14871254',
        'doi': '10.5281/zenodo.14871254',
        'version': 'source-data.zip.',
        'licence': 'Creative Commons Attribution 4.0 (Zenodo licence field).',
        'licence_url': 'https://creativecommons.org/licenses/by/4.0/',
        'licence_note': 'Open licence; derived tiles are public.',
        'cite': 'Nordic Spatial Humanities, Zenodo, https://doi.org/10.5281/zenodo.14871254',
        'area': 'Nordic countries, Iceland.',
        'period': 'Middle Ages; saga places dated by the saga age they describe.',
        'contents': 'Cult places with first attestation and medieval diocese; saga places with type; chronicle attestations.',
        'processed': 'Nordic churches, chapels, monasteries with a first attestation and saga places (764) → public tiles and place index.',
    },
    'tib-maps-of-power': {
        'name': 'TIB "Maps of Power: Historical Atlas of Places, Borderzones and Migration Dynamics in Byzantium" (OpenAtlas)',
        'source': 'Tabula Imperii Byzantini, Austrian Academy of Sciences (ÖAW).',
        'page': 'https://maps-of-power.oeaw.ac.at/ (API: https://openatlas.maps-of-power.at/api/)',
        'doi': '',
        'version': 'API snapshot (5,522 places in 56 pages of 100).',
        'licence': 'Not stated for the data (only photographs are marked CC BY 4.0). Licence not verified.',
        'licence_url': 'https://maps-of-power.oeaw.ac.at/',
        'licence_note': 'LOCAL USE ONLY until the ÖAW confirms a data licence.',
        'cite': 'Tabula Imperii Byzantini, Maps of Power (ÖAW), https://maps-of-power.oeaw.ac.at/',
        'area': 'Byzantine Balkans and Greece (TIB volumes), with medieval church case studies elsewhere (e.g. Slovakia).',
        'period': '4th–15th centuries, with dated attestations (earliest/latest).',
        'contents': 'Places in Linked Places format: names, types (urban/rural settlement, fortification, church, monastery…), attestation timespans, geometry (points or areas).',
        'processed': 'Local-only tiles (2,809 places with a location).',
    },
    'dk-fund-og-fortidsminder': {
        'name': 'Fund og Fortidsminder — Danish register of ancient monuments (GeoPackage)',
        'source': 'Slots- og Kulturstyrelsen (Danish Agency for Culture and Palaces).',
        'page': 'https://www.kulturarv.dk/fundogfortidsminder/Download/',
        'doi': '',
        'version': 'FF.zip as downloaded (server date 2026-09-30).',
        'licence': 'Not stated on the download page (checked 2026-10-01). Licence not verified.',
        'licence_url': 'https://www.kulturarv.dk/fundogfortidsminder/Download/',
        'licence_note': 'LOCAL USE ONLY until the licence is confirmed. (The first audit pass recorded "CC0" without evidence; corrected.)',
        'cite': 'Slots- og Kulturstyrelsen, Fund og Fortidsminder.',
        'area': 'Denmark.',
        'period': 'All periods, by period class.',
        'contents': 'GeoPackage and QGIS project of the national register of ancient monuments and finds.',
        'processed': 'Not yet processed (raw only).',
    },
}

MANUAL = {
    'gb1900': {
        'name': 'GB1900 Complete Gazetteer',
        'status': 'SKIPPED FOR NOW — the repository owner chose not to add GB1900 (30 September 2026). Do not download it until asked.',
        'why': 'Skipped by choice. For reference: the only download is on the Vision of Britain site (https://www.visionofbritain.org.uk/data/), which did not respond from the build environment (connection timed out). The NLS Data Foundry page for GB1900 only links back to Vision of Britain.',
        'action': 'None for now. If it is wanted later: open https://www.visionofbritain.org.uk/data/#tabgb1900 in a browser, download the COMPLETE gazetteer (about 2.55 million rows, CSV), and place the unchanged file in original/ here.',
        'licence': 'Conflicting statements: search summaries of the Vision of Britain page say CC BY-SA 4.0; the NLS Data Foundry page says CC0. Record whatever the downloaded file and its page say.',
        'area': 'England, Wales and Scotland.',
        'period': 'Ordnance Survey six-inch 2nd edition maps, 1888–1914.',
    },
    'kepn': {
        'name': 'Key to English Place-Names (KEPN)',
        'status': 'EXTERNAL REFERENCE ONLY — no legitimate bulk download.',
        'why': 'The official site (https://kepn.nottingham.ac.uk/, Institute for Name-Studies, University of Nottingham) offers search and browse only. No download, export or API is offered; the site says "© 2026 University of Nottingham. All Rights Reserved"; and its robots.txt disallows automated access to everything except /about. Scraping it would break those terms.',
        'action': 'None. Use it as an online source (link to its search page for a place-name). If bulk use is ever needed, ask the Institute for Name-Studies for permission.',
        'licence': 'All rights reserved.',
        'area': 'England (pre-1974 counties).',
        'period': 'Names of cities, towns and villages, most of them "well over a thousand years old" (KEPN about page).',
    },
    'pase': {
        'name': 'PASE — Prosopography of Anglo-Saxon England',
        'status': 'EXTERNAL REFERENCE ONLY — no downloadable dataset, and the licence does not permit copying.',
        'why': 'The official site (https://pase.ac.uk/) offers no download or export. Its copyright page says: "All material is made available free of charge for individual, non-commercial use only, provided this publication is acknowledged. … All other use is prohibited without the express written consent of the Project Directors."',
        'action': 'None. Link to PASE person records instead of copying them. Copying the database would need written consent from the Project Directors.',
        'licence': 'Individual, non-commercial use only; all other use needs written consent.',
        'area': 'Anglo-Saxon England.',
        'period': 'Anglo-Saxon period to the late 11th century, including people recorded in Domesday Book.',
    },
}


def human(n):
    for unit in ('bytes', 'KB', 'MB', 'GB'):
        if n < 1024 or unit == 'GB':
            return f'{n:.0f} {unit}' if unit == 'bytes' else f'{n:.1f} {unit}'
        n /= 1024


def write_gitignore(manifest):
    # Keep downloaded files out of git unless they are recorded and small;
    # large ones are restored by fetch.py from their official URLs.
    # Datasets whose licence does not allow (or has not been shown to allow) republishing stay out of the
    # public repository whatever their size (sources.json: "local_only": true).
    local = {d['id'] for d in json.load(open(os.path.join(ROOT, 'sources.json'))) if d.get('local_only')}
    small = sorted(k for k, v in manifest.items() if v['bytes'] <= LARGE and k.split('/')[0] not in local)
    lines = ['# Generated by scripts/historical-data/describe.py', '*.lock', '*.part', '*.tmp',
             'raw/*/original/**', 'raw/*/nightly-export/**', 'raw/*/derived-*.json', '!raw/*/original/**/', '!raw/*/nightly-export/**/']
    lines += [f'!raw/{k}' for k in small]
    open(os.path.join(ROOT, '.gitignore'), 'w').write('\n'.join(lines) + '\n')


def main():
    manifest = json.load(open(os.path.join(ROOT, 'manifest.json')))
    write_gitignore(manifest)
    for ds, d in DATASETS.items():
        folder = os.path.join(RAW, ds)
        os.makedirs(folder, exist_ok=True)
        rows = sorted((k[len(ds) + 1:], v) for k, v in manifest.items() if k.startswith(ds + '/'))
        dates = sorted({v['downloaded'] for _, v in rows})
        total = sum(v['bytes'] for _, v in rows)
        lines = [
            f"# {d['name']}", '',
            f"- **Official source:** {d['source']}",
            f"- **Dataset page:** {d['page']}",
        ]
        if d['doi']:
            lines.append(f"- **DOI:** {d['doi']}")
        lines += [
            f"- **Version / date:** {d['version']}",
            f"- **Licence:** {d['licence']} — {d['licence_url']} (see LICENSE.md)",
            f"- **Geographic coverage:** {d['area']}",
            f"- **Historical date range:** {d['period']}",
            f"- **Download date:** {', '.join(dates) if dates else 'not yet downloaded'}",
            f"- **Total size:** {human(total)} in {len(rows)} files",
            '', '## What it contains', '', d['contents'], '',
            *(['## Processed into Shelf', '', d['processed'], ''] if d.get('processed') else []),
            *(['## Known limitations', '', d['limitations'], ''] if d.get('limitations') else []),
            '## Files', '',
            'Saved unchanged in `original/` (or `nightly-export/`). Files over 25 MB are not stored in git; run `python3 scripts/historical-data/fetch.py ' + ds + '` to download them again and check them against these SHA-256 checksums.',
            '', '| File | Size | In git | Download URL | SHA-256 |', '| --- | --- | --- | --- | --- |',
        ]
        for path, v in rows:
            lines.append(f"| `{path}` | {human(v['bytes'])} | {'yes' if v['bytes'] <= LARGE else 'no'} | {v['url']} | `{v['sha256']}` |")
        notes = [(path, v) for path, v in rows if v.get('provenance') or v.get('corroborated_by')]
        if notes:
            lines += ['', '### Provenance', '']
            for path, v in notes:
                lines.append(f"- `{path}`: {' '.join(x for x in (v.get('provenance'), v.get('corroborated_by')) if x)}")
        missing = [f['path'] for s in json.load(open(os.path.join(ROOT, 'sources.json'))) if s['id'] == ds for f in s['files'] if f"{ds}/{f['path']}" not in manifest]
        if missing:
            lines += ['', '**Not yet downloaded:** ' + ', '.join(f'`{m}`' for m in missing)]
        lines += ['', '## How to cite', '', d['cite'], '']
        open(os.path.join(folder, 'SOURCE.md'), 'w').write('\n'.join(lines))
        lic = [f"# Licence — {d['name']}", '', f"**{d['licence']}**", '', d['licence_url'], '']
        if d['licence_note']:
            lic += [d['licence_note'], '']
        lic += ['Required attribution:', '', d['cite'], '']
        open(os.path.join(folder, 'LICENSE.md'), 'w').write('\n'.join(lic))
    for ds, d in MANUAL.items():
        folder = os.path.join(RAW, ds)
        os.makedirs(folder, exist_ok=True)
        lines = [
            f"# {d['name']}", '', f"**{d['status']}**", '',
            f"- **Why:** {d['why']}",
            f"- **What to do:** {d['action']}",
            f"- **Licence:** {d['licence']}",
            f"- **Geographic coverage:** {d['area']}",
            f"- **Historical date range:** {d['period']}",
            '- **Checked on:** 2026-09-29 (GB1900 status updated 2026-09-30)' if ds == 'gb1900' else '- **Checked on:** 2026-09-29', '',
        ]
        open(os.path.join(folder, 'SOURCE.md'), 'w').write('\n'.join(lines))


if __name__ == '__main__':
    main()
